# Generated by Django 3.2.5 on 2021-08-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polling_app', '0002_polls_questions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='polls',
            old_name='questions',
            new_name='question1',
        ),
        migrations.AddField(
            model_name='polls',
            name='questNumber',
            field=models.CharField(default=1, max_length=2),
        ),
        migrations.AddField(
            model_name='polls',
            name='question2',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='polls',
            name='question3',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='polls',
            name='question4',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='polls',
            name='question5',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='polls',
            name='question6',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='polls',
            name='question7',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='polls',
            name='question8',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
