# Generated by Django 3.2.5 on 2021-08-14 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polling_app', '0006_auto_20210814_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polls',
            name='answer',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
