# Generated by Django 3.2.6 on 2021-08-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polling_app', '0007_alter_polls_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='polls',
            name='owner',
            field=models.CharField(default='nobody', max_length=200),
        ),
    ]
